name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Build Universal Release APK
        env:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_SECRET: ${{ secrets.LASTFM_SECRET }}
          API_BEARER_TOKEN: ${{ secrets.API_BEARER_TOKEN }}
          TOGETHER_BEARER_TOKEN: ${{ secrets.TOGETHER_BEARER_TOKEN }}
          CANVAS_BEARER_TOKEN: ${{ secrets.CANVAS_BEARER_TOKEN }}
          EXTRACTOR_BEARER: ${{ secrets.EXTRACTOR_BEARER }}
        run: |
          ./gradlew assembleGmsMobileUniversalRelease \
            --stacktrace \
            --scan \
            --no-daemon

      - name: Sign APK
        if: success()
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: app/build/outputs/apk/gmsMobileUniversal/release
          signingKey: ${{ secrets.KEYSTORE }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: FrostSoul-Universal-Release
          path: |
            app/build/outputs/apk/**/release/*signed.apk
            app/build/outputs/apk/**/release/*.apk
